/**
 * Shared English UI strings for Dawat RMG SOFT.
 */
export const bn = {
  brand: "Dawat RMG SOFT",
  brandSub: "From order confirmation to shipment — one ERP.",

  add: "Add new",
  save: "Save",
  cancel: "Cancel",
  edit: "Edit",
  update: "Update",
  view: "Details",
  delete: "Delete",
  close: "Close",
  search: "Search",
  reset: "Reset",
  applyFilter: "Apply filter",
  exportPdf: "Export PDF",
  exportExcel: "Export Excel",
  actions: "Actions",
  status: "Status",
  all: "All",
  noData: "No records match the selected filter.",
  required: "Required",
  loading: "Loading...",
  totalRecords: "Total records",
  details: "Details",
  notes: "Notes",
  from: "From",
  to: "To",

  buyers: {
    heading: "Buyer list",
    subtitle: "Order and payment history",
    newBuyer: "New buyer",
    name: "Buyer name",
    company: "Company",
    phone: "Phone",
    email: "Email",
    address: "Address",
    searchPlaceholder: "Search by name, company, or phone...",
    totalOrders: "Total orders",
    totalValue: "Total value",
    totalDue: "Total due",
    totalReceived: "Total received",
    orderHistory: "Order history",
    paymentHistory: "Payment history",
    selectBuyerHint: "Select a buyer to see details",
    noBuyers: "No buyers found",
  },

  orders: {
    heading: "Style / PO Orders",
    subtitle: "Export order tracking — buyer PO, style, quantity and lifecycle status",
    newOrder: "New order",
    searchOrder: "Search orders",
    searchPlaceholder: "PO, buyer or style...",
    selectBuyer: "Select buyer",
    buyer: "Buyer",
    po: "PO number",
    style: "Style",
    product: "Product name",
    color: "Color",
    qty: "Quantity (pcs)",
    unitPrice: "Unit price",
    shipDate: "Shipment date",
    stage: "Production stage",
    orderValue: "Order value",
    progress: "Progress",
    taStatus: "T&A status",
    paymentStatus: "Payment status",
  },

  ta: {
    heading: "T&A Calendar",
    subtitle: "Time & Action — order-wise task timeline from confirmation to shipment",
    totalTasks: "Total tasks",
    delayed: "Delayed",
    inProgress: "In progress",
    completed: "Completed",
    tableView: "Table view",
    timelineView: "Timeline view",
    highRiskOnly: "High risk only",
    delayedOnly: "Delayed only",
    todaysTasks: "Today's tasks",
    searchOrder: "Search orders",
    searchPlaceholder: "PO, style or buyer name...",
    taskStatus: "Task status",
    department: "Department",
    plannedFrom: "Planned date (from)",
    plannedTo: "Planned date (to)",
    riskLevel: "Risk level",
    taskName: "Task name",
    owner: "Owner",
    plannedDate: "Planned date",
    actualDate: "Actual date",
    updateStatus: "Update status",
  },

  merch: {
    heading: "Merchandising",
    subtitle: "Buyer communication, tech pack, sample approval and order lifecycle",
    orderTracking: "Order Tracking",
    sampleApproval: "Sample Approval",
    runningStyles: "Running styles",
    atRisk: "At risk",
    ppPending: "PP pending",
    techPackApproved: "Tech pack approved",
    searchOrder: "Search orders",
    searchPlaceholder: "PO, buyer, style...",
    riskLevel: "Risk level",
    fitSample: "Fit sample",
    ppSample: "PP sample",
    productionApproval: "Production approval",
    techPackStatus: "Tech pack status",
  },

  costing: {
    heading: "Costing & Consumption",
    subtitle: "Fabric consumption, trims, CM, washing/printing and profit margin per style",
    costedStyles: "Costed styles",
    avgMargin: "Average margin",
    selectStyle: "Select style",
    searchCosting: "Search costing",
    searchPlaceholder: "Buyer, style, fabric...",
    fabricDetails: "Fabric details",
    fabricName: "Fabric name",
    gsm: "GSM",
    consumption: "Consumption (yd/pc)",
    fabricCost: "Fabric cost",
    trimsCost: "Trims cost",
    cmCost: "CM cost",
    washCost: "Wash/print cost",
    totalCost: "Total cost",
    unitPrice: "Unit price",
    margin: "Margin",
    breakdown: "Cost breakdown",
  },

  procurement: {
    heading: "Procurement Management",
    subtitle: "Fabric and trims booking, supplier PO tracking and in-house status",
    fabricBooking: "Fabric booking",
    trimsBooking: "Trims booking",
    supplierPo: "Supplier PO",
    inhouseStatus: "In-house status",
    newBooking: "New booking",
    searchPlaceholder: "Supplier, item, PO or style...",
    supplier: "Supplier",
    item: "Item",
    selectOrder: "Select order",
    required: "Required qty",
    received: "Received qty",
    balance: "Balance",
    expectedDate: "Expected date",
    receivedDate: "Received date",
    totalBookings: "Total bookings",
    inHousePct: "In-house %",
    delayedBookings: "Delayed bookings",
    pendingBalance: "Pending qty",
  },

  inventory: {
    heading: "Inventory Management",
    subtitle: "Fabric, trims and finished goods stock with full ledger tracking",
    fabricStock: "Fabric stock",
    trimsStock: "Trims stock",
    cuttingIssue: "Cutting issue",
    finishedGoods: "Finished goods",
    stockLedger: "Stock ledger",
    newItem: "New item",
    searchPlaceholder: "Item, PO, style or buyer...",
    itemName: "Item name",
    colorSpec: "Color / specification",
    location: "Location",
    received: "Received",
    issued: "Issued",
    balance: "Balance",
    totalBalance: "Total balance",
    lowStock: "Low stock items",
    totalItems: "Total items",
  },

  production: {
    cutting: {
      heading: "Cutting Section",
      subtitle: "Fabric issue, cut quantity, rejection and running balance per order",
      fabricIssued: "Fabric issued",
      cutQty: "Cut qty",
      reject: "Reject",
      balance: "Balance",
      totalCut: "Total cut",
      totalReject: "Total reject",
      inProgress: "In progress",
      completed: "Completed",
    },
    sewing: {
      heading: "Sewing Line Efficiency",
      subtitle: "Target vs output, defect rate and line-wise efficiency tracking",
      target: "Target",
      output: "Output",
      defect: "Defect",
      operators: "Operators",
      efficiency: "Efficiency",
      avgEfficiency: "Average efficiency",
      totalOutput: "Total output",
      belowTarget: "Below target",
    },
    finishing: {
      heading: "Finishing Section",
      subtitle: "Iron, finish and reject tracking — ready for packing quantity",
      fromSewing: "Received from sewing",
      iron: "Iron",
      finish: "Finish",
      reject: "Reject",
      readyForPacking: "Ready for packing",
      totalReady: "Total ready",
    },
    packing: {
      heading: "Packing Section",
      subtitle: "Carton packing, color/size breakdown and ready-to-ship quantity",
      color: "Color",
      size: "Size",
      cartons: "Cartons",
      packed: "Packed",
      ready: "Ready",
      totalCartons: "Total cartons",
      totalPacked: "Total packed",
    },
  },
};

export type BnDict = typeof bn;
